project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Welcome to my blog!"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/#/
      - icon: github
        href: https://github.com/DennisxB
      - icon: gear-fill
        href: https://linktr.ee/#
      - icon: twitter
        href: https://twitter.com/#
format:
  html:
    theme: lux
    css: styles.css

editor: visual

